default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  username: <%= ENV.fetch("POSTGRES_USER", "mconf_biblioteca") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "mconf_biblioteca") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: mconf_biblioteca_development

test:
  <<: *default
  database: mconf_biblioteca_test

production:
  <<: *default
  database: mconf_biblioteca_production
